### ISSUE TITLE
Slows down local development a lot

### ISSUE THREAD

**Issue by elie222** [mzohaibqc/antd-live-theme#2]
Page reloads take a long time while using this package.

For now I've commented out the config and less files and this makes page reload much faster while in local dev. I wonder if there's a better solution though, and why things take so long to reload while using this package.

**Comment by mzohaibqc** [comment]
@elie222 It takes time because on every build/compilation, `color.less` file is generated. This repo is an example project using `react-app-rewire-antd-theme`  which internally uses `antd-theme-webpack-plugin`. You can use core script `https://github.com/mzohaibqc/antd-theme-generator` to generate color.less when you need to generate that instead of generating new file after each change.

**Comment by mzohaibqc** [comment]
@elie222 I've added a new parameter `generateOnce` which you can pass in config/options. Default value is `false` and `colro.less` will be generated on each compilation/build but setting it to `true` , it will only generate `color.less` once which will reduce build time on every change. But if you have some changes in your styles/less files then you need to restart build process `npm start` etc. to reflect those changes in `color.less`. I hope this will help.   Let me k now if you still have any issue.

**Comment by elie222** [comment]
Awesome!

Will update soon! Sounds great

**Comment by sureshokp** [comment]
@mzohaibqc where i want to pass `generateOnce = true` parameter

**Comment by elie222** [comment]
It's in the docs. I believe like so:

indexFileName: 'index.html',
// this makes dev faster, but should be switched off if you want to edit
the theme
// see here for more:
https://github.com/mzohaibqc/react-app-rewire-antd-theme#note-generateonce-false
generateOnce: true,
}

**Comment by sureshokp** [comment]
@elie222 still slow to change  theme

**Comment by mzohaibqc** [comment]
@elie222 I would recommend using core script that is being used with inside that package which will allow you to generate `color.less` file according to your needs. This is the repo and same npm package name. https://github.com/mzohaibqc/antd-theme-generator

Have a look at create example https://github.com/mzohaibqc/antd-theme-generator/tree/master/examples/create-react-app
