### ISSUE TITLE
@text-color are not update in dynamically

### ISSUE THREAD

**Issue by sureshokp** [mzohaibqc/antd-live-theme#3]
`const path = require('path');
const { updateConfig } = require('react-app-rewire-antd-theme');

const options = {
    stylesDir: path.join(__dirname, './src/styles'),
    antDir: path.join(__dirname, './node_modules/antd'),
    varFile: path.join(__dirname, './src/styles/variables.less'),
    mainLessFile: path.join(__dirname, './src/styles/index.less'),
    themeVariables: ['@primary-color', '@secondary-color', '@text-color', '@text-color-secondary', '@heading-color'],
    indexFileName: 'index.html'
}
module.exports = function override(config, env) {
    config = updateConfig(config, env, options)
    return config;
};`

**> this is my config-override.js file.
here i give themeVariables array for five colors. only @primary-color and @heading-color are updated in  dynamically but @text-color not updated dynamically and also @layout-header-color, @layout-body-color, @layout-sider-color are not updated dynamically** @mzohaibqc  pls help me

**Comment by mzohaibqc** [comment]
@sureshokp I'll look into this. For now, you can clone this project and see how `@text-color` is working in this project. What are you doing differently... 

`git clone https://github.com/mzohaibqc/antd-live-theme.git`

Here is demo deployed on firebase and @text-color is updating: https://antd-live-theme.firebaseapp.com/

**Comment by mzohaibqc** [comment]
@sureshokp I searched variables that you mentioned `@layout-header-color, @layout-body-color, @layout-sider-color`  but those are not  Ant Design color variables. Actual color variales end with `background`  word and not with `color`,e.g.  `@layout-body-background`
Here are those lines from Ant Design `default.less` file
```
// Layout
@layout-body-background      : #f0f2f5;
@layout-header-background    : #001529;
@layout-footer-background    : @layout-body-background;
@layout-sider-background     : @layout-header-background;
```

**Comment by sureshokp** [comment]
@mzohaibqc sorry that is typing mistakes. I gave variables are end with background only. 
i gave` @layout-body-background` and `@text-color` in variables.less file. it working fine but dynamically changing  `window.less.modifyVars(vars)` time. not updating `@text-color` and ` @layout-body-background `colors.

**Comment by mzohaibqc** [comment]
@sureshokp I've updated code which generates `color.less` which actually is responsible to dynamic theme. It's much better and there were some scenarios that were not handles. I've fixed those. Clone this repo and see how this is setup. Here is live demo with following color variables
```[
    '@primary-color',
    '@secondary-color',
    '@text-color',
    '@text-color-secondary',
    '@heading-color',
    '@layout-body-background',
    '@btn-primary-bg',
    '@layout-header-background'
  ]```

I hope it will help :)

**Comment by sureshokp** [comment]
@mzohaibqc  Working fine now,  Thanks a lot

**Comment by mzohaibqc** [comment]
@sureshokp Glad to help :)
