### ISSUE TITLE
New idea - dynamic css while changing variables.less file.

### ISSUE THREAD

**Issue by mpiorowski** [mzohaibqc/antd-live-theme#8]
First of all, amazing work, been searching for this solution for over 3 months.
All works great using window.less.modifyVars(vars).

Amazing feature would be if You could make it also change the css while changing the variables.less file without the need to recompile whole project.

**Comment by mzohaibqc** [comment]
@mpiorowski Thank you so much.  Such appreciation keeps me motivated :) 
I could not understand about the feature you are suggesting. Can you elaborate a little bit more?

Thanks.

**Comment by mpiorowski** [comment]
What i mean is whenever You do some changes inside variables.less files to the global antd variabless (like @prmiary-color), You need to recompile the project to see the changes. It would be amazing if the project would automatically update the css in the whole project. The only way to do it right now without recompile is by using  window.less.modifyVars(vars).

**Comment by mzohaibqc** [comment]
@mpiorowski if you use https://github.com/mzohaibqc/antd-theme-webpack-plugin you don't need to re-run npm start etc. Code will automatically recompile and a new color.less file will be generated in public folder you. You might need to reload the page.

Have a look at this example. This is based on `create-react-app v1` but it will work the same in `create react-app v2`.
https://github.com/mzohaibqc/antd-theme-webpack-plugin/tree/master/examples/create-react-app

**Comment by mpiorowski** [comment]
@mzohaibqc tried everything, but still cannot make it work :( i don't know if it's important, but after dev recompile i don't see anywhere color.less file. Should it appear somewhere or not?

If You would have some time, pls could You look at this and maybe make an example? After all, working solution is so important for fast css changes that in my opinion it should be on official Antd page.

**Comment by mpiorowski** [comment]
@mzohaibqc ok, new discovery :D If i make a change inside variables.less file, css will not update. BUT if i make a change in variables.less file AND THEN MAKE ANY change in index.less, the css updates :)

**Comment by mpiorowski** [comment]
So in the end my conclusion is that the mainLessFile variable inside rescriptsrc.js file is responsible for recompiling color.less file. And the project is watching that file. So my solution was just to put variables.less path into both varFile and mainLessFile variables. Works wonderfully :) Once again, amazing job, this sollution should be on main antd page for dynamic theme. :) Closing issue.

**Comment by mzohaibqc** [comment]
@mpiorowski Awesome, glad that you found a solution.

This is in Ant Design's docs on Theming page but at the bottom of the page so most of you don't get there 😄 

Ant Design and Ant Design Pro use this plugin as well. Ant Design Pro uses an extra plugin due to `css-modules` to transform class names.
