### ISSUE TITLE
There is an official theme editor

### ISSUE THREAD

**Issue by mindplay-dk** [mzohaibqc/antd-live-theme#9]
There's an [official theme editor](https://www.antdtheme.com/default) available.

I don't know why they don't advertise it on the home page - I found it by accident.

So you might want to consider deprecating this project, and/or link from the README to the official editor, which is much more complete. (Your project ranks highly in search results on Google, so you might help others find it.)

**Comment by veeral-patel** [comment]
Thank you for sharing @mindplay-dk!

I was trying to get dark mode working with this repo, to no avail.

**Comment by mzohaibqc** [comment]
@mindplay-dk These two projects do different jobs. This project provides unlimited possibilities of color scheme right in your browser but the one you shared just creates a static one theme that can be used in other projects. This project is to create a dynamic theme.
